NUM_SEGMENTS_IN_LANE = 140
NUM_SEGMENTS_IN_ROUTE = 25
NUM_POLYGONS = 10
NUM_LINE_STRINGS = 60
MAX_NUM_NEIGHBORS = 320
MAX_NUM_AGENTS = MAX_NUM_NEIGHBORS + 1  # Including ego
POINTS_PER_LANELET = 20
POINTS_PER_POLYGON = 40
POINTS_PER_LINE_STRING = 20
POLYGON_TYPE_NUM = 1
LINE_STRING_TYPE_NUM = 2
# Number of columns in a segment matrix
# (X,Y,dX,dY,LeftBoundX,LeftBoundY,RightBoundX,RightBoundY,TrafficLightEncoding(Dim5),Speed Limit)
TRAFFIC_LIGHT_ONE_HOT_DIM = 5

EGO_AGENT_PAST_IDX_X = 0
EGO_AGENT_PAST_IDX_Y = 1
EGO_AGENT_PAST_IDX_COS = 2
EGO_AGENT_PAST_IDX_SIN = 3

LINE_TYPE_NUM = 10
# Index for each field
X = 0
Y = 1
dX = 2
dY = 3
LB_X = 4
LB_Y = 5
RB_X = 6
RB_Y = 7
TRAFFIC_LIGHT = 8
TRAFFIC_LIGHT_GREEN = 8
TRAFFIC_LIGHT_YELLOW = 9
TRAFFIC_LIGHT_RED = 10
TRAFFIC_LIGHT_WHITE = 11
TRAFFIC_LIGHT_NO_TRAFFIC_LIGHT = 12
LINE_TYPE_LEFT_START = 13
LINE_TYPE_RIGHT_START = LINE_TYPE_LEFT_START + LINE_TYPE_NUM
SEGMENT_POINT_DIM = LINE_TYPE_RIGHT_START + LINE_TYPE_NUM

INPUT_T = 30
OUTPUT_T = 80  # Output timestamp number
POSE_DIM = 4  # x, y, cos(yaw), sin(yaw)

OUTPUT_SHAPE = (1, MAX_NUM_AGENTS, OUTPUT_T, POSE_DIM)

TURN_INDICATOR_OUTPUT_NONE = 0
TURN_INDICATOR_OUTPUT_DISABLE = 1
TURN_INDICATOR_OUTPUT_ENABLE_LEFT = 2
TURN_INDICATOR_OUTPUT_ENABLE_RIGHT = 3
TURN_INDICATOR_OUTPUT_KEEP = 4
TURN_INDICATOR_OUTPUT_DIM = 5
TURN_INDICATOR_LOGIT_SHAPE = (1, TURN_INDICATOR_OUTPUT_DIM)

SAMPLED_TRAJECTORIES_SHAPE = (1, MAX_NUM_AGENTS, OUTPUT_T + 1, POSE_DIM)
EGO_HISTORY_SHAPE = (1, INPUT_T + 1, POSE_DIM)
EGO_CURRENT_STATE_SHAPE = (1, 10)
NEIGHBOR_SHAPE = (1, MAX_NUM_NEIGHBORS, INPUT_T + 1, 11)
STATIC_OBJECTS_SHAPE = (1, 5, 10)
LANES_SHAPE = (1, NUM_SEGMENTS_IN_LANE, POINTS_PER_LANELET, SEGMENT_POINT_DIM)
LANES_HAS_SPEED_LIMIT_SHAPE = (1, NUM_SEGMENTS_IN_LANE, 1)
LANES_SPEED_LIMIT_SHAPE = (1, NUM_SEGMENTS_IN_LANE, 1)
ROUTE_LANES_SHAPE = (1, NUM_SEGMENTS_IN_ROUTE, POINTS_PER_LANELET, SEGMENT_POINT_DIM)
ROUTE_LANES_HAS_SPEED_LIMIT_SHAPE = (1, NUM_SEGMENTS_IN_ROUTE, 1)
ROUTE_LANES_SPEED_LIMIT_SHAPE = (1, NUM_SEGMENTS_IN_ROUTE, 1)
GOAL_POSE_SHAPE = (1, POSE_DIM)
EGO_SHAPE_SHAPE = (1, 3)
TURN_INDICATORS_SHAPE = (1, INPUT_T)
